# POST http://localhost:3003/api/blogs
# Content-Type: application/json

# {
#   "title": "Intro to Angular",
#   "author": "Hassan B. Nurudeen",
#   "url": "nurubika.com/intro-to-angular",
#   "likes": 7000,
#   "userId": "66d0a4aec1e18a228a30e43f" 
# }




# POST   http://localhost:3003/api/users
# Content-Type: application/json


# {
#   "username": "Bika",
#   "name": "NurudeenBika",
#   "password": "hassan"
# }

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Bika",
  "password": "hassan"
}